export const free = {
  title: "Free",
  description: "Upgrade to a paid plan for additional features and support",
  buttonText: "FREE",
  plan_type: "free",
  legend: "Limited set of core features",
  highlighted: false,
  priceAmount: "$0",
  features: [
    "Up to 1 dynamic QR code",
    "No additional Dynamic QR codes are allowed",
    "Unlimited pre-generated QRs",
    "Up to 1 microsite (mobile-friendly landing page)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};

export const basic = {
  title: "Basic",
  description: "For small businesses/freelancers at an affordable price",
  buttonText: "SUBSCRIBE",
  plan_type: "basic",
  legend: "A good choice to get started",
  highlighted: false,
  priceAmount: "$9.00",
  features: [
    "Up to 50 dynamic QR codes",
    "$1 per aditional Dynamic QR",
    "Unlimited pre-generated QRs",
    "Up to 50 microsites (mobile-friendly landing pages)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};
export const basicAnnual = {
  title: "Basic",
  description: "A good choice to get started and save some cash.",
  buttonText: "SUBSCRIBE",
  plan_type: "basicAnnual",
  legend: "Save two months",
  highlighted: false,
  priceAmount: "$90.00",
  features: [
    "Up to 5 Dynamic QR codes",
    "$1 per aditional Dynamic QR",
    "Unlimited pre-generated QRs",
    "Up to 5 microsites (mobile-friendly landing pages)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};

export const business = {
  title: "Business",
  description: "For medium businesses who need a larger solution",
  buttonText: "SUBSCRIBE",
  plan_type: "business",
  legend: "Have plenty of room to grow.",
  highlighted: true,
  priceAmount: "$15.00",
  features: [
    "Up to 100 dynamic QR codes",
    "$0.90 per aditional Dynamic QR",
    "Unlimited pre-generated QRs",
    "Up to 100 microsites (mobile-friendly landing pages)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};
export const businessAnnual = {
  title: "Business",
  description: "Receive a fair discount with our annual plan.",
  buttonText: "SUBSCRIBE",
  plan_type: "businessAnnual",
  legend: "Save three months",
  highlighted: true,
  priceAmount: "$135.OO",
  features: [
    "Up to 100 dynamic QR codes",
    "$0.90 per aditional Dynamic QR",
    "Unlimited pre-generated QRs",
    "Up to 100 microsites (mobile-friendly landing pages)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};

export const premium = {
  title: "Premium",
  description: "The definitive plan. You're completely covered.",
  buttonText: "SUBSCRIBE",
  plan_type: "premium",
  legend: "Best price",
  highlighted: true,
  priceAmount: "$45.00",
  features: [
    "Up to 500 dynamic QR codes",
    "$0.80 per additional Dynamic QR",
    "Unlimited pre-generated QRs",
    "Unlimited microsites (mobile-friendly landing pages)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};
export const premiumAnnual = {
  title: "Premium",
  description: "Receive a great discount and get completely covered.",
  buttonText: "SUBSCRIBE",
  plan_type: "premiumAnnual",
  legend: "Save four months",
  highlighted: true,
  priceAmount: "$360.00",
  features: [
    "Up to 500 dynamic QR codes",
    "$0.80 per additional Dynamic QR",
    "Unlimited pre-generated QRs",
    "Up to 500 microsites (mobile-friendly landing pages)",
    "Unlimited static QR codes",
    "Unlimited scans",
    "QR codes design customization and edition",
    "Dynamic QR codes content edition",
    "Microsites appearance customization and edition",
  ],
};

export default { free, basic, business, premium };